source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!

target "ALPersonalDemo" do

#富文本
pod 'YYText', '~> 1.0.5'
#图片缓存
pod 'SDWebImage'
#AutoLayout
pod 'Masonry', '~> 1.0.1'
#刷新控件
pod 'MJRefresh', '~> 3.1.12'
pod 'AFNetworking', '~> 3.0.4'
pod 'ReactiveCocoa', '2.5'
end
